export const UserActionTypes = {
    FETCH_USERS: "FETCH_USERS",
    GET_USERS: 'GET_USERS',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',
    DELETE_USER: 'DELETE_USER',
}